### ISSUE TITLE
BIG ISSUE

### ISSUE THREAD

**Issue by markknol** [macronauts/haxe-macro-workshop-2015#1]
Just kidding :stuck_out_tongue_winking_eye: 

This workshop was really nice! Thanks, while I already knew something about macros it was very helpful to see you do it, I've learned a lot and some cool tricks too.

This "issue" can be closed.

**Comment by ruby0x1** [comment]
:o:

**Comment by jasononeil** [comment]
:+1:

Glad you liked it! Feel free to add issues or pull requests for anything you think is unclear, could be explained better, more comments in the worked solutions etc.
